### PR TITLE
feature importance piplines

### PR DESCRIPTION
**Pull request by erikerlandson**
Adds ML pipelines for feature importance, spark core and pyspark

### CODE REVIEW

**Comment by erikerlandson** [comment]
cc @willb

**Comment by erikerlandson** [comment]
Going to play with an alternate implementation that uses RDD and map-partitions instead of UDAFs.  May be simpler and a bit faster.

**Comment by erikerlandson** [comment]
I can't work out a way to implement the `withColumn` formulation of this without incurring O(M^2) on account of needing to copy feature vector for each feature replacement

**Comment by erikerlandson** [comment]
I favor merging the current implementation in the interest of making forward progress.  If I or somebody else figures out a way to do this at the `transform` level that scales and doesn't choke the query planner, I can always update it at a later date

**Comment by willb** [comment]
Agreed; I think, at this point, figuring out how to do this in the data frame space is an interesting exercise at most.

**Pull request merged**
